[package]
name = "systemcheck"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/a2-ai/systemcheck"

[dependencies]
num_cpus = "1.17.0"
libc = "0.2"
humanize-bytes = "1.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
